[tool.poetry]
name = "pymake"
version = "0.1.0"
description = "一个基于函数式编程用于生成cmake文件的python库"
authors = ["Zengtudor"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
